services:
  - type: web
    name: backend
    runtime: node
    buildCommand: cd Backend && npm install
    startCommand: cd Backend && npm start
    envVars:
      - key: PORT
        value: 3000
      - key: NODE_ENV
        value: production

  - type: web
    name: frontend
    runtime: node
    buildCommand: cd frontend && npm install && npm run build
    startCommand: npx serve -s frontend/dist -l 3000
    envVars:
      - key: VITE_API_URL
        generateValue: true
